#!/usr/local/bin/perl
use strict; use warnings;
###########################
# CP - copy a list of files
use File::Copy;
my ($list, $target, $dump) = @ARGV;
die "ARG1 list ARG2 target ARG3 dump" if (!defined $dump);
$dir =~ s%/\z%%;

open(my $lfh, '<', $list);
my @list = readline $lfh;
close $lfh; chomp @list;
my $cnt = 0;

for my $line (@list)
{
  $cnt++;
  if (-e $f)
    { copy($f, $dump) or print "$f FAIL cnt: $cnt\n"; }
}
